### ISSUE TITLE
Update boostrap.py also in branches

### ISSUE THREAD

**Issue by jcerjak** [collective/tutorial.todoapp#13]
Currently, setup http://tutorialtodoapp.readthedocs.org/en/latest/chapter_0.html#tutorial-setup fails, because chapter1 branch doesn't contain the latest bootstrap which was added to master.

**Comment by criticalboot** [comment]
Hi jcerjak, how to make this work?

**Comment by jcerjak** [comment]
@zupo ?

**Comment by zupo** [comment]
Use 'virtualenv' instead of 'bin/virtualenv'. I need to fix it, sorry for the delay.

**Comment by criticalboot** [comment]
Hi, I am a beginner  and trying to learn plone. Please help me to fix the following...

criticalboot@criticalboot:~/tutorial.todoapp$ ./bin/buildout
Getting distribution for 'buildout-versions==1.7'.
Got buildout-versions 1.7.
Getting distribution for 'mr.developer==1.21'.
Got mr.developer 1.21.
While:
  Installing.
  Loading extensions.

An internal error occured due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/criticalboot/tutorial.todoapp/eggs/zc.buildout-2.1.0-py2.7.egg/zc/buildout/buildout.py", line 1923, in main
    getattr(buildout, command)(args)
  File "/home/criticalboot/tutorial.todoapp/eggs/zc.buildout-2.1.0-py2.7.egg/zc/buildout/buildout.py", line 445, in install
    self._load_extensions()
  File "/home/criticalboot/tutorial.todoapp/eggs/zc.buildout-2.1.0-py2.7.egg/zc/buildout/buildout.py", line 979, in _load_extensions
    ep.load()(self)
  File "/home/criticalboot/tutorial.todoapp/eggs/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 2013, in load
    entry = __import__(self.module_name, globals(),globals(), ['**name**'])
  File "/home/criticalboot/tutorial.todoapp/eggs/buildout_versions-1.7-py2.7.egg/buildout_versions/**init**.py", line 14, in <module>
    from zc.buildout.easy_install import is_distribute
ImportError: cannot import name is_distribute

**Comment by zupo** [comment]
The cause of this is most likely an outdated version of boostrap.py: recently zc.buildout 2.0 was released and on boostrap is trying to use it and it fails. 

Try replacing bootstrap.py with this one and try again: http://downloads.buildout.org/1/bootstrap.py

**Comment by criticalboot** [comment]
Hi Zupo,
    I am unable to buildout zodb3.. how to make this work? It  is saying that Python.h file is missing but I cant figured it out where to correct this.

Getting distribution for 'ZODB3==3.10.5'.
In file included from src/BTrees/_OOBTree.c:32:0:
src/BTrees/BTreeModuleTemplate.c:15:20: fatal error: Python.h: No such file or directory
compilation terminated.
error: Setup script exited with error: command 'gcc' failed with exit status 1
An error occurred when trying to install ZODB3 3.10.5. Look above this message for any errors that were output by easy_install.
While:
  Installing.
  Getting section instance.
  Initializing section instance.
  Installing recipe plone.recipe.zope2instance.
  Getting distribution for 'ZODB3==3.10.5'.
Error: Couldn't install: ZODB3 3.10.5

**Comment by zupo** [comment]
I think this means you are missing Python development (header) files on your system. Something like ``apt-get install python-dev` on Debian should install them. Also see this for more pointers: http://developer.plone.org/reference_manuals/active/deployment/preparing.html

**Comment by zupo** [comment]
Done.
